name: Deploy to Netlify
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Netlify にデプロイメント
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: '.'
          production-deploy: true
          deploy-message: ${{ github.event.head_commit.message || github.event.pull_request.title }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PERSONAL_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROJECT_ID }}